keep-starknet-strange/art-peace

- docker-compose.yml
- indexer/Dockerfile
Switch from installing apibara into ubuntu to using the apibara webhook image
> dev: Patch Apibara indexer for docker compose

- onchain/src/art_peace.cairo
- onchain/src/interface.cairo
- onchain/src/quests/interface.cairo
- onchain/src/quests/pixel_quest.cairo
- onchain/src/tests/art_peace.cairo
- postgres/init.sql
Add calldata to quests to allow easier implementation of generic quests
> feat: Quests call data

- frontend/src/App.js
- frontend/src/canvas/Canvas.js
- frontend/src/canvas/SelectedPixelPanel.css
- frontend/src/canvas/SelectedPixelPanel.js
- Replaced hardcoded `placed_by` value in the `Owner` field with address data
> feat: display owner of selected pixel

- backend/core/backend.go
- backend/core/databases.go
- backend/go.mod
- backend/routes/indexer.go
Fix bug with concurrent access to postgres by switching to a pool
> bug: Backend Postgres parallel access

- backend/routes/user.go
Adding getUserName backend route
> feat: getUsername backend route fixes  #49

- .all-contributorsrc
- README.md
Update latest contributors on the project
> contribs: Add latest contributors

- onchain/src/lib.cairo
- onchain/src/mocks/unruggable_token.cairo
- onchain/src/quests/interfaces.cairo
- onchain/src/quests/unruggable_quest.cairo
- onchain/src/tests/art_peace.cairo
> feat: create an Unruggable Meme quest

- backend/routes/user.go
- frontend/src/App.js
Made an api call to get the number of pixels a user has
> feat: fetching extra pixels a user has from the backend

- backend/config/backend.go
- backend/routes/websocket.go
- configs/backend.config.json
- configs/docker-backend.config.json
I added the websocket Upgrader to the backend.config.json file. Now I'm moving on to parsing the config on the backend.
> added websocket upgrader to the backend config file

- backend/routes/user.go
- frontend/src/tabs/Account.js
> Feature: Load username on frontend

- backend/routes/quests.go
-  issue #77 
-  Get large dayIndex from Days table
-  Get today's quest  
expected payload for getTodayQuest
```
[
{
"key": 3,
"name": "Quest 3",
"description": "Description for Quest 3",
"reward": 200,
"dayIndex": 2
}
]
```
> Feat: get today quest

- backend/routes/quests.go
- issue #78
- get completed quests from UserDailyQuests table
- get completed quests from UserMainQuests table
expected payload for /getCompletedMainQuests
```
[
{
"key": 2,
"name": "Quest 3",
"description": "Description for Quest 3",
"reward": 200,
"dayIndex": 2
}
]
```
expected payload for /getCompletedDailyQuests
```
[
{
"key": 2,
"name": "Quest 3",
"description": "Description for Quest 3",
"reward": 200,
"dayIndex": 2
}
]
```
> feat(backend): implement get completed quests

- backend/go.mod
- backend/routes/nft.go
- postgres/init.sql
- like NFT
- Unlike NFT
- Get like on NFT by NFT Key
expected payload for like and unlike NFT Endpoint
```
{
"nftkey": 750,
"useraddress": "ddhdhfnjggnhj"
}
```
> Ft:  like  AND unlike NFT

- backend/routes/user.go
- frontend/src/canvas/Canvas.js
- frontend/src/canvas/PixelSelector.js
- issue #70
- create last time tracker backend route
- consume last time tracker on the frontend
expected payload for getLastPlacedPixelTime route
```
{
"time": "2023-01-05T10:30:00Z"
}
```
> feat: Last placed time tracker 

- backend/routes/routes.go
- backend/routes/votableColors.go
- configs/canvas.config.json
- frontend/src/App.js
- frontend/src/configs/backend.config.json
- frontend/src/configs/canvas.config.json
- frontend/src/services/apiService.js
- frontend/src/tabs/TabPanel.js
- frontend/src/tabs/Voting.js
- frontend/src/utils/TimerInjector.js
- postgres/init.sql
- tests/integration/docker/initialize.sh
- tests/integration/local/run.sh
**Backend: /routes/votableColors**
1. Created a new route for managing votable colors (`votableColors`).
2. Added an endpoint to add new votable colors.
3. Added an endpoint to fetch votable colors based on votes.
**Frontend:**
- Updated files:
1. `App.js`: I implemented a function to fetch votable colors from the backend. Additionally, I removed the timer's useEffect because it causes all child components to re-render with each tick, resulting in repeated API calls triggered on every tick.
2. `tabs/tabPanel`: Updated to consume the new Timer Component.
3. `voting.js`: Consumed the votableColors endpoint data
4. `utils.js/timer`: Created a custom render Props component for timer countdown.
- New additions:
1. Created a new utility function (`TimerInjector render props`) to manage …
> [feat] Load color votes from Postgres 

- backend/core/databases.go
- backend/routes/pixel.go
- frontend/src/tabs/canvas/SelectedPixelPanel.js
> feat: read username on getPixelInfo

- frontend/src/tabs/quests/QuestItem.css
- frontend/src/tabs/quests/QuestItem.js
- frontend/src/tabs/quests/Quests.js
- frontend/src/utils/Styles.css
- frontend/src/utils/encodeToLink.js
This PR added a function to encode links in quests description
> Quests description links formatting

- frontend/src/tabs/quests/QuestItem.css
- frontend/src/tabs/quests/QuestItem.js
Added smooth animations and transitions when ever the quest form is opened or closed.
> feat: animation on open/close of quest form

- frontend/src/tabs/quests/QuestItem.js
Implemented Quest address hex checker
> feat: quest address hex checker

- onchain/src/lib.cairo
- onchain/src/quests/authority_quest.cairo
- onchain/src/quests/interfaces.cairo
- onchain/src/tests/authority_quest.cairo
> [FEAT] Quest : Authority Quest

- backend/routes/templates.go
- postgres/init.sql
Postgresql tables have been changed:
- add `TemplateData` table
- add foreign key to `TemplateData` in `Templates`
Manual test have been done with the following curl calls:
```shell
curl --silent http://localhost:8080/add-template-img -X POST --form "image=@/tmp/art/file1.png"
curl --silent http://localhost:8080/add-template-img -X POST --form "image=@/tmp/art/file2.png"
```
I have check if DB have been updated using `psql` shell:
```
art-peace-db=# select * from templates;
key | name | width | height | position | reward |                           reward_token                           | template_id 
-----+------+-------+--------+----------+--------+------------------------------------------------------------------+-------------
1 |      |    50 |     28 |        0 |      0 | RWRD …
```
> [feat]: #48 store template data in postgres

- frontend/src/App.js
- frontend/src/canvas/CanvasContainer.js
- frontend/src/canvas/NFTSelector.js
- frontend/src/canvas/TemplateBuilderPanel.js
- frontend/src/footer/PixelSelector.js
- frontend/src/services/apiService.js
- frontend/src/tabs/account/Account.js
- frontend/src/tabs/canvas/ExtraPixelsPanel.js
- frontend/src/tabs/nfts/NFTs.js
- frontend/src/tabs/templates/Templates.js
Refactored fetch calls to make use of Async Await in the project.
> refac: fetch calls to async/await

- backend/routes/indexer.go
- backend/routes/pixel.go
- frontend/src/App.css
- frontend/src/tabs/canvas/ExtraPixelsPanel.js
Changed the extra pixels place devnet function to take position and color as arguments.
>  extra pixels devnet position formatting

- frontend/src/tabs/TabPanel.css
- frontend/src/tabs/account/Account.js
-Added username edit functionality
> Added username edit functionality

- onchain/src/art_peace.cairo
- onchain/src/lib.cairo
- onchain/src/quests/authority_quest.cairo
- onchain/src/quests/interfaces.cairo
- onchain/src/quests/nft_quest.cairo
- onchain/src/quests/pixel_quest.cairo
- onchain/src/quests/rainbow_quest.cairo
- onchain/src/quests/template_quest.cairo
- onchain/src/quests/unruggable_quest.cairo
- onchain/src/tests/pixel_quest.cairo
> [dev] Refactor quests assertions and events

- backend/config/backend.go
- backend/routes/utils/responses.go
- backend/routes/websocket.go
- configs/backend.config.json
- configs/docker-backend.config.json
CORS Logic added such that cors values are now dynamically loaded from a JSON.
> [refac] CORS Configuration Logic for API

- frontend/src/App.js
- frontend/src/canvas/CanvasContainer.js
- frontend/src/tabs/TabPanel.js
- frontend/src/tabs/canvas/ExtraPixelsPanel.js
> feat: extra pixel highlighter

- backend/routes/nft.go
Added pagination to getNFTs and getMyNFTs endpoints, allowing page and pageLength query parameters with a default of 25 and a maximum of 50.
> [feat]: Backend functionality for NFT pagination

- backend/routes/user.go
- frontend/src/tabs/TabPanel.js
- frontend/src/tabs/voting/Voting.js
implemented a route to get users color votes
> feat:get user color votes

- backend/routes/indexer/route.go
- docker-compose.yml
- indexer/Dockerfile
- indexer/script.js
addresses the issue of persisting that the user ID accross containers restarts
> feat: keep track of block and indexer cursor

- backend/routes/nft.go
> feat: return nftlikes

- onchain/src/art_peace.cairo
- onchain/src/interfaces.cairo
- onchain/src/lib.cairo
- onchain/src/quests/vote_quest.cairo
- onchain/src/tests/vote_quest.cairo
-  A daily quest that checks if a user has voted or a color to be added to the pallet or not
- The day index was used to query for user color for that particular day.
> feat: vote quest

- backend/quests/inputs.go
- backend/quests/quests.go
- backend/quests/status.go
- backend/routes/quests.go
- configs/production-quests.config.json
- configs/quests.config.json
- frontend/src/App.js
- postgres/init.sql
quest progress configs, storing init params in postgres, and corresponding routes.
> feat: Quest progression

- .all-contributorsrc
- README.md
> Contrib: add latest contributors

- frontend/src/tabs/nfts/NFTItem.js
Added functionality to the nft share button to be able to share NFT image on twitter.
> NFT share button PR

- backend/core/backend.go
- backend/routes/indexer/nft.go
- backend/routes/indexer/pixel.go
- backend/routes/nft.go
- onchain/src/nfts/canvas_nft.cairo
- onchain/src/tests/art_peace.cairo
> feat: implement NFTJson Metadata

- onchain/README.md
> chore:fix typo

- onchain/src/art_peace.cairo
- onchain/src/interfaces.cairo
- onchain/src/lib.cairo
- onchain/src/quests/faction_quest.cairo
- onchain/src/quests/interfaces.cairo
- onchain/src/tests/faction_quest.cairo
> feat: implement faction quest

- frontend/src/canvas/CanvasContainer.js
> chore:fix comment

- backend/quests/inputs.go
- backend/quests/quests.go
- backend/quests/status.go
- configs/production-quests.config.json
- configs/quests.config.json
> feat: Quest Status Checker: Vote Quest 

- onchain/src/lib.cairo
- onchain/src/nfts/canvas_nft.cairo
- onchain/src/nfts/interfaces.cairo
function that dispatch event for like and unlike NFT
> Work on Onchain NFT likes/dislikes

- backend/routes/nft.go
- frontend/src/services/apiService.js
- frontend/src/tabs/nfts/NFTs.js
> feat: NFTs Explorer: Top NFTs

- backend/quests/quests.go
- backend/quests/status.go
> feat: Faction status checker

- backend/routes/indexer/route.go
- backend/routes/indexer/votableColors.go
- backend/routes/votableColors.go
- indexer/prod-script.js
- indexer/script.js
- onchain/src/art_peace.cairo
- postgres/init.sql
- tests/integration/docker/initialize.sh
- tests/integration/local/run.sh
> feat: add AddVotableColor events

- backend/routes/nft.go
- frontend/src/services/apiService.js
- frontend/src/tabs/nfts/NFTs.js
I created a new route and function that shows the newest NFTs first.
> showing NFTs in Descending order

- backend/quests/quests.go
- backend/quests/status.go
- configs/quests.config.json
- Implements the CheckNftStatus whichc checks if there is any NFT minted by the user. If there is, it returns 1, 1, else returns 0, 1.
- Refactored Name of NftQuestType and NftQuest to NFTMintQuest everywhere for consistency.
> Quest Status Tracker: NFT Quest

- backend/quests/inputs.go
- backend/quests/status.go
> feat:CheckHodlStatus

- frontend/src/tabs/TabPanel.js
- frontend/src/tabs/factions/Factions.js
- frontend/src/tabs/nfts/NFTItem.js
- frontend/src/tabs/nfts/NFTs.js
> Bug: Fix missing props

- backend/routes/indexer/nft.go
- frontend/src/footer/PixelSelector.js
- After placing a pixel and timer reaches 0, it automatically pull up the color selector menu again
- Saved Images of NFTs minted are scaled up 10x (you can confirm this by inspecting the minted images on your browser)
> UI updates

- onchain/src/art_peace.cairo
- onchain/src/interfaces.cairo
- onchain/src/tests/art_peace.cairo
> refactor(onchain):  refactor `like_nft`, `unlike_nft` and add test

- backend/routes/templates.go
- frontend/pnpm-lock.yaml
- frontend/public/index.html
- frontend/src/App.js
- frontend/src/footer/PixelSelector.css
- frontend/src/footer/PixelSelector.js
- frontend/src/index.css
- frontend/src/tabs/TabPanel.js
- frontend/src/tabs/account/Account.js
- frontend/src/tabs/canvas/ExtraPixelsPanel.js
- frontend/src/tabs/canvas/SelectedPixelPanel.js
- frontend/src/tabs/factions/FactionItem.js
- frontend/src/tabs/nfts/NFTItem.js
- frontend/src/tabs/nfts/NFTMintingPanel.js
- frontend/src/tabs/nfts/NFTs.js
- frontend/src/tabs/quests/QuestItem.js
- frontend/src/tabs/quests/Quests.js
- frontend/src/tabs/templates/EventItem.js
- frontend/src/tabs/templates/FactionTemplateBuilderPanel.js
- frontend/src/tabs/voting/VoteItem.js
- frontend/src/tabs/voting/Voting.js
- frontend/src/utils/TimerInjector.js
> Template Defender

- Makefile
- backend/Dockerfile.websocket.prod
- frontend/src/App.js
- frontend/src/canvas/CanvasContainer.js
- infra/art-peace-infra/templates/backend/backend-ingress.yaml
- infra/art-peace-infra/values.yaml
> Websocket deployment

- configs/canvas.config.json
- frontend/src/canvas/CanvasContainer.js
- frontend/src/configs/canvas.config.json
> Non-worlds home screen
